S3 Audits
Medaxion/audited_s3 pull request #1
Opened 2018-06-25 18:38 UTC by aualdrich

* Implement auditable and associated audits
* Refactor auditor to forward calls to audits collection to an S3 Proxy service.
  This fixes usages such as object.audits.create() or object.audits.new() that previously relied on Active Record's collection proxy to managed chained methods. Instead, we now forward these calls to the S3AuditorProxy, which will lazily evaluate calls to S3, but still allow Active Record like calls.
* Add ability to call audits.descending/ascending
* Add ability to call .associated_audits, as well as any other deferrable action.
* Implement own_and_associated_audits
* Implement audits.exists, audits.fund_by, audits.where, audits.from
* Implement Audit.update, Audit.update_column, Audit.update_attributes
* Separate multiple audits in the same file via a new line rather than using the JSON array brackets.
  This is because the AWS Athena service expects this.
* Ensure we manage all created_at timestamps using UTC.
* Add partitioning support.
* Update VCR files.
* Ensure we cleanup S3 test files before each run.
* Update README
* Add "stub_responses" option for testing.
* Implement up_until and revision_at for S3.
* Implement Audit.create(attrs)
* Implement == for audits when in s3 mode.
* Implement delete_all for S3 auditing (only if in test mode!!)
* Add shortcut to access s3_key directly from an audit.
* Forward update_column call to update_attributes call for consistency.
* Update modify_audit to handle scenario where changing the associated attribute on an existing audit needs to move the audit to its new location.
* Ensure that when reading .audits for an object that we pull from auditable_type_audits and associated_type_audits. This is because there could be audits that existed before an object got associated to another object later on. In this case, there would need to be audits spread out across two files.
* Add s3 stub for delete_object.
* Implement Audit.count when in S3 + stub_responses mode. This is useful when checking audits created in the scope of a unit test.
* If created_at is specified when writing an audit, use that.
* Instead of trying to find out if an object exists in S3 via pulling the whole object down and deserializing it, use the HEAD operation in S3.
* Minimize instantiations of S3 Proxy classes.
* If we don't have an id to partition by, just return '?'

2018-06-25 18:43 UTC, aualdrich commented
@jsgarvin Don't worry about the merge conflicts. This repo is a fork of the original, so there's nothing really to merge per-se. I just created an "orig" branch to compare it against so that all my changes show up.

2018-06-26 17:25 UTC, jsgarvin requested changes

2018-06-26 17:25 UTC, jsgarvin commented on lib/audited/audit.rb
> +        other_object.request_uuid == self.request_uuid
Should this line have a `&&` at the end?

2018-06-26 17:25 UTC, jsgarvin commented on lib/audited/audit.rb
> +        other_object.created_at = self.created_at
Let's indent all but the first line in this `if` block to emphasize that it's a single expression.  eg.

    other_object.auditable_id == self.auditable_id &&
      other_object.auditable_type == self.auditable_type &&
      other_object.associated_id == self.associated_id &&
      etc.

2018-06-26 17:25 UTC, jsgarvin commented on lib/audited/auditor.rb
> +      end
I don't understand the need for this, but I'm sure there's a good one.  :smiley:   Can you help me understand?

2018-06-26 17:25 UTC, jsgarvin commented on spec/audited/audit_spec.rb
Out of curiosity, what does this do?

2018-06-26 17:25 UTC, jsgarvin commented on README.md
> +
What happens if someone updates this setting after some audits have already been stored.  For instance, we write a bunch of 'Customer' audits before remembering that we want to partition them.   Any reason not to just always partition everything?

2018-06-26 20:40 UTC, aualdrich commented on lib/audited/audit.rb
> +        other_object.request_uuid == self.request_uuid
Wow, great catch! There's also a bug in "created_at" down below. It is using single equals instead of double equals.

2018-06-26 20:40 UTC, aualdrich commented on lib/audited/audit.rb
> +        other_object.created_at = self.created_at
Great idea!

2018-06-26 20:43 UTC, aualdrich commented on lib/audited/auditor.rb
> +      end
Actually, there's not lol. There was going to be. I was going to put the conditional logic for persistence here but ended up encapsulating it in the S3AuditorProxy. That allows the app to call "audits.create" and have it be agnostic to the underlying storage mechanism. I can take this out.

2018-06-26 20:53 UTC, aualdrich commented on spec/audited/audit_spec.rb
This is a gem that detects the number of lines of code that are covered/uncovered. It's not really accurate, though. It works by looking at the described class and finding lines that it thinks aren't covered. However, in my case I have another test file that covers the tests for the lines it thinks are uncovered. By saying "uncovered: 41" it says that I know there are an existing 41 lines in the file that are uncovered, but if there are any more than that, report them at the end of the test run.

2018-06-26 21:00 UTC, aualdrich commented on README.md
> +
In that case it would only find the ones that match the current settings. So if you set a particular model like cases to start being partitioned, it will now look in auditable_type_audits/cases/0_9999/1.audits instead of auditable_type_audits/cases/1.audits. We would then need to run a conversion script to move the old, unpartitioned ones into the new partition schema.  This script would exist as part of this ticket: https://www.wrike.com/open.htm?id=208980045 

Not partitioning everything is by design. The Write task lists only certain types of files that we need to be partitioned.

2018-06-27 19:25 UTC, aualdrich commented
@jsgarvin Fixed the issues you mentioned!

2018-06-28 18:35 UTC, jsgarvin commented on README.md
> +
Ok, I had a chat with JT and Tracy and we decided to make a change to partition all models by default.   We may still want a way in the future to explicitly exclude a model from partitioning, so if that's an easy swap, then cool.  But we definitely want it to partition any new models by default without anybody having to remember to add it to the configuration.  I hope that's not a difficult change, and sorry for the confusion.   Thank You!  :+1: :beer: :rocket:

2018-06-28 19:53 UTC, aualdrich commented on README.md
> +
@jsgarvin Okay, great point. For the gem, it's a very straightforward swap to partition by default. I'll make that change and update the PR. No problem at all! I didn't think about just doing it by default. Love it!

Note that we'll need to update the audit converter utility to respect this logic as well when it's writing out to S3. It sounds like it's missing some data, though, so it likely needs to be re-run anyway.

2018-06-28 22:07 UTC, jsgarvin approved these changes

2018-06-28 22:07 UTC, jsgarvin commented on README.md
> +
Should probably update this to reflect the change in partitioning behavior.  Otherwise, I think it looks good.

2018-07-03 15:03 UTC, closed without merging

2018-07-03 15:04 UTC, aualdrich commented
Closing PR since it's been approved and changes are already in master.